/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Networking Fundamentals',
      collapsed: false,
      items: [
        'networking-fundamentals/what-is-http',
        'networking-fundamentals/http-vs-https',
        'networking-fundamentals/dns-basics',
        'networking-fundamentals/tcp-ip-basics',
        'networking-fundamentals/ports-and-sockets',
        'networking-fundamentals/reverse-proxy',
        'networking-fundamentals/load-balancing',
        'networking-fundamentals/tls-termination',
        'networking-fundamentals/request-lifecycle',
        'networking-fundamentals/container-networking',
        'networking-fundamentals/why-ingress-exists',
      ],
    },
    {
      type: 'category',
      label: 'Traefik Core',
      collapsed: false,
      items: [
        'traefik-core/traefik-overview',
        'traefik-core/entrypoints',
        'traefik-core/routers',
        'traefik-core/services',
        'traefik-core/middlewares',
        'traefik-core/providers',
        'traefik-core/static-vs-dynamic-config',
        'traefik-core/dashboard',
        'traefik-core/docker-provider',
        'traefik-core/file-provider',
        'traefik-core/acme-and-letsencrypt',
        'traefik-core/tls-certificates',
        'traefik-core/kubernetes-ingress',
      ],
    },
    {
      type: 'category',
      label: 'Hands-on Labs',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Lab 1: Basic Routing',
          items: [
            'hands-on-labs/basic-routing/README',
            'hands-on-labs/basic-routing/architecture',
            'hands-on-labs/basic-routing/exercises',
            'hands-on-labs/basic-routing/troubleshooting',
          ],
        },
        'hands-on-labs/host-based-routing/README',
        'hands-on-labs/path-based-routing/README',
        'hands-on-labs/https-lab/README',
        'hands-on-labs/middlewares/README',
        'hands-on-labs/rate-limiting/README',
        'hands-on-labs/authentication/README',
        'hands-on-labs/load-balancing/README',
        'hands-on-labs/observability/README',
      ],
    },
    {
      type: 'category',
      label: 'Internals',
      collapsed: true,
      items: [
        'internals/docker-event-watching',
        'internals/service-discovery',
        'internals/routing-table-generation',
        'internals/middleware-chains',
        'internals/tls-handshake',
        'internals/certificate-renewal',
        'internals/dynamic-config-reloads',
        'internals/performance-considerations',
        'internals/websocket-handling',
        'internals/request-buffering',
      ],
    },
    {
      type: 'category',
      label: 'Debugging & Troubleshooting',
      collapsed: true,
      items: [
        'debugging/access-logs',
        'debugging/debug-logs',
        'debugging/prometheus-metrics',
        'debugging/tracing',
        'debugging/debugging-404s',
        'debugging/debugging-502s',
        'debugging/debugging-tls',
        'debugging/docker-network-debugging',
        'debugging/kubernetes-debugging',
        'debugging/security-best-practices',
      ],
    },
    {
      type: 'category',
      label: 'Production Architecture',
      collapsed: true,
      items: [
        'production-architecture/multi-service-apps',
        'production-architecture/high-availability',
        'production-architecture/api-gateway-patterns',
        'production-architecture/blue-green-deployments',
        'production-architecture/canary-deployments',
        'production-architecture/zero-downtime-deployments',
        'production-architecture/kubernetes-production',
        'production-architecture/ci-cd-integration',
        'production-architecture/microservices-networking',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'cheatsheets/docker-commands',
        'cheatsheets/traefik-cli',
        'cheatsheets/curl-debugging',
        'cheatsheets/troubleshooting-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Diagrams & Assets',
      collapsed: true,
      items: [
        'diagrams/reverse-proxy-flow',
        'diagrams/tls-handshake',
        'diagrams/docker-networking',
        'diagrams/traefik-routing',
      ],
    },
  ],
};

module.exports = sidebars;
